image:
  file: .gitpod.Dockerfile
tasks:
  - name: React
    before: cd /workspace/rust-typescript-react/react
    init: npm i
    command: |
      export HMR_HOST=`gp url 8080`
      npm run start

  - name: Rust
    before: cd /workspace/rust-typescript-react/rust
    init: cargo build
    command: wasm-pack build
    openMode: split-right

ports:
  - port: 8080
    onOpen: open-browser
    description: Website preview
    visibility: public
