image:
  file: .gitpod.Dockerfile
tasks:
  - name: React
    before: cd /workspace/rust-typescript-react/react
    init: npm i
    command: npm run start

  - name: Rust
    before: cd /workspace/rust-typescript-react/rust
    init: cargo build
    command: cargo watch -x run
    openMode: split-right

ports:
  - port: 3000
    onOpen: open-preview
    description: Website preview
