export const presetCatalog = [
  {
    id: 'clean-bright-everyday',
    label: 'Clean Bright Everyday',
    inspiredBy: 'A6',
    style: 'bright, neutral, clean',
    bestFor: 'daylight, cafes, neutral outfits, clean indoor shots',
    settings: {
      filterStrength: 7.2,
      exposure: 0.3,
      contrast: -0.5,
      saturation: -0.5,
      temperature: -0.5,
      sharpen: 1,
      grain: 1,
    },
  },
  {
    id: 'warm-soft-lifestyle',
    label: 'Warm Soft Lifestyle',
    inspiredBy: 'A4',
    style: 'warm, soft, lifestyle',
    bestFor: 'portraits, golden hour, lifestyle, soft skin tones',
    settings: {
      filterStrength: 6.2,
      exposure: 0.5,
      contrast: -1,
      saturation: -0.5,
      temperature: 0.8,
      tint: 0.3,
      fade: 1,
      grain: 1,
    },
  },
  {
    id: 'moody-street',
    label: 'Moody Street',
    inspiredBy: 'HB2',
    style: 'dark, moody, urban',
    bestFor: 'night shots, street photography, rainy scenes, dark outfits',
    settings: {
      filterStrength: 7.1,
      exposure: -0.7,
      contrast: 1,
      saturation: -1,
      temperature: -0.5,
      shadows: 1,
      grain: 2,
    },
  },
  {
    id: 'crisp-color-pop',
    label: 'Crisp Color Pop',
    inspiredBy: 'C8',
    style: 'vibrant, sharp, punchy',
    bestFor: 'travel, food, blue skies, colorful architecture',
    settings: {
      filterStrength: 5,
      exposure: 0.2,
      contrast: 0.8,
      saturation: 0.5,
      temperature: -0.3,
      sharpen: 1,
      clarity: 1,
    },
  },
  {
    id: 'film-portrait',
    label: 'Film Portrait',
    inspiredBy: 'KP5',
    style: 'muted, film-like, portrait',
    bestFor: 'portraits, fashion, muted tones, editorial headshots',
    settings: {
      filterStrength: 6,
      exposure: 0.3,
      contrast: -0.5,
      saturation: -0.8,
      temperature: 0.5,
      fade: 1,
      grain: 2,
    },
  },
  {
    id: 'vintage-faded-feed',
    label: 'Vintage Faded Feed',
    inspiredBy: 'M5',
    style: 'vintage, faded, soft',
    bestFor: 'retro looks, casual lifestyle, fashion, soft color scenes',
    settings: {
      filterStrength: 5,
      exposure: 0.4,
      contrast: -1.2,
      saturation: -1,
      temperature: 0.5,
      fade: 2,
      grain: 2,
      vignette: 0.5,
    },
  },
  {
    id: 'minimal-black-and-white',
    label: 'Minimal Black and White',
    inspiredBy: 'B1',
    style: 'monochrome, minimal, crisp',
    bestFor: 'architecture, portraits, shadows, minimal compositions',
    settings: {
      filterStrength: 8,
      blackAndWhite: 1,
      contrast: 1,
      exposure: 0.2,
      fade: 1,
      grain: 1,
      sharpen: 1,
    },
  },
  {
    id: 'soft-cool-editorial',
    label: 'Soft Cool Editorial',
    inspiredBy: 'S2',
    style: 'cool, muted, editorial',
    bestFor: 'fashion, window light, minimal interiors, cool-toned feeds',
    settings: {
      filterStrength: 5,
      exposure: 0.2,
      contrast: -0.5,
      saturation: -1,
      temperature: -0.8,
      fade: 1,
      grain: 1,
    },
  },
  {
    id: 'selfie-portrait',
    label: 'Selfie Portrait',
    inspiredBy: 'A4',
    style: 'warm, flattering, social',
    bestFor: 'selfies, portraits, social posts',
    quick: true,
    settings: {
      filterStrength: 6.5,
      exposure: 0.4,
      contrast: -0.8,
      saturation: -0.5,
      temperature: 0.7,
      fade: 1,
      grain: 1,
    },
  },
  {
    id: 'beach-travel',
    label: 'Beach Travel',
    inspiredBy: 'C8',
    style: 'sunny, crisp, vacation',
    bestFor: 'travel, beach, summer, daylight',
    quick: true,
    settings: {
      filterStrength: 5,
      exposure: 0.3,
      contrast: 0.5,
      saturation: 0.3,
      temperature: -0.4,
      sharpen: 1,
    },
  },
  {
    id: 'night-out',
    label: 'Night Out',
    inspiredBy: 'HB2',
    style: 'dark, nightlife, punchy',
    bestFor: 'nightlife, street, clubs, low light',
    quick: true,
    settings: {
      filterStrength: 7,
      exposure: -0.6,
      contrast: 1,
      saturation: -1,
      shadows: 1,
      grain: 2,
    },
  },
];
