name: Publish to NPM
on:
  release:
    types: [created]

jobs:
  build-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          target: wasm32-unknown-unknown
          toolchain: stable
          override: true
      - run: cd rust
      - uses: actions-rs/cargo@v1
      - name: cargo-build
        run: cargo build
      - name: wasm-build
        run: wasm-pack build
      - name: wasm-publish
        run: wasm-pack publish
        with:
          access: public
          token: ${{ secrets.NPM_TOKEN }}