name: Publish to NPM

on:
  release:
    types: [created]

permissions:
  contents: read
  id-token: write

jobs:
  build-publish:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./rust

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 24
          registry-url: https://registry.npmjs.org/

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          target: wasm32-unknown-unknown

      - name: Install wasm-pack
        run: cargo install wasm-pack

      - name: Cargo tests
        run: cargo test

      - name: Cargo build
        run: cargo build --release

      - name: wasm-pack build
        run: wasm-pack build --target bundler --out-dir pkg --release

      - name: wasm-pack publish
        run: wasm-pack publish --access public
